baseURL = 'https://khaister.github.io/'
languageCode = 'en-us'
title = "Hi, I'm Khai!"
theme = 'salinger'

[params]
author = 'Khai Nguyen'
twemoji = true
text404 = ''

# theme
homeIcon = '<i class="fa-solid fa-house"></i>'
mainMenuIcon = '<i class="fa-solid fa-bars"></i>'
themeIcon = '<i class="fa-regular fa-sun"></i>'

mainMenuShowThemes = true
showFooterOnHomepage = true
showHeaderOnHomepage = true
showSocialOnHomepage = true
showOnlyFeaturedPost = true

filterCoverImages = true

[params.footer]
copy = 'Khai Nguyen —'

[[params.social]]
name = "github"
url = 'https://github.com/khaister'
icon = 'fa-brands fa-github'
featured = true                     # true to be displayed in the home hero

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/khainguyen"
icon = "fa-brands fa-linkedin"
featured = true


[Menu]
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1
[[menu.main]]
name = "Contact"
url = "mailto:khai.nguyen@outlook.com"
weight = 2


[taxonomies]
category = "categories"
lang = "langs"
tags = "tags"
tool = "tools"


# the following code is mandatory for the theme to work properly
[module]
[module.hugoVersion]
extended = false
min = "v0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cacheBusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cacheBusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cacheBusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cacheBusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'base16-snazzy'
