name: Résumé > Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: resume/khai_nguyen.typ

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update
        run: |
          git config --global user.name 'Khai Nguyen'
          git config --global user.email '1192669+khaister@users.noreply.github.com'
          git add resume/khai_nguyen.pdf
          git commit -S -m "🤖 Update khai_nguyen.pdf"
          git push
