name: Publish Résumé - Merge Pull Request

on:
  # Runs on pushes targeting the automation/update-cv branch
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [automation/update-cv]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        run: |
          gh pr merge --squash
          # echo "PR_NUMBER=$(gh pr view --json number | jq .number)" >> $GITHUB_ENV
